### ISSUE TITLE
Invalid Signer Error for the one created using Wallet method in Ethers

### ISSUE THREAD

**Issue by MidhunKRaj** [Open-Attestation/token-registry#11] opened 2020-08-26 07:05 UTC
Hi,

    I have been working on the token registry integration in which I used the Signer(both based on private key and on mnemonics). I am getting an invalid message when I tried using the ethers. It was successful in the document verification (open-attestation)process with the document store and I could issue the certificate. But the same Signer is showing invalid error. Please check the attached image for the further details about the error. Kindly help me.
<img width="735" alt="trade trust issue" src="https://user-images.githubusercontent.com/45687173/91271795-5c6e5000-e798-11ea-8a3d-a709ee57d035.png">
.

**Comment by Nebulis** [comment] 2020-08-26 10:10
duplicate of https://github.com/TradeTrust/tradetrust-website/issues/223

**Closed by Nebulis** 2020-08-26 10:10 UTC
