### ISSUE TITLE
Using the `--factory` flag still uses the default provided factory contract

### ISSUE THREAD

**Issue by marlowl** [Open-Attestation/token-registry#163] opened 2023-03-22 15:53 UTC
### Possible issue

I tried to deploy a token contract using the following commands on the Mumbai testnet:

```bash
npx hardhat deploy:factory --network mumbai

// Token Factory deployment is successful... 
// Token Factory address: 0x160B0AcF4E665e4b45f41A46ab1054E8cA8bD53d

npx hardhat deploy:token --name ABC --symbol ABC --factory 0x160B0AcF4E665e4b45f41A46ab1054E8cA8bD53d  --network mumbai
```

However, I didn't see any `Events` or `Internal Txns` logging at the [factory contract address](https://mumbai.polygonscan.com/address/0x160B0AcF4E665e4b45f41A46ab1054E8cA8bD53d). Upon further inspection, it appears that the deployment used the default factory contract address provided [here](https://github.com/Open-Attestation/token-registry/blob/master/src/constants/contract-address.ts#L15), as evidenced by the `titleEscrowFactory` data log [here](https://mumbai.polygonscan.com/tx/0xba7c558f0673d31f45e0300ed26c298dda9fe1a16250093175052688154f95d6#eventlog).

### Questions
- Is above written problem the expected or intended sequence of actions?
- As a v4 implementer, I'm wondering if it is recommended to use the default factory contracts or if it would be 'cleaner' to create my own factory contract. I noticed there are already quite a few [constant contract addresses](https://github.com/Open-Attestation/token-registry/blob/master/src/constants/contract-address.ts#L9) present, but I'm not sure if those should be used as well.

Could you provide some guidance on this matter? Thank you! 😄

**Comment by superical** [comment] 2023-03-22 17:02
Hi @marlowl! Yes, it's using the default factory contract by design. I'd think that the benefits of using the default factory are that:
1. It's a little more convenient; one step lesser to get things up and running!
2. You save on the gas fees for deploying an identical copy of the default factory

However, if you wish to have different behaviours from the default one, you will have to deploy your own copy of it and pass its address to the deploy command via the `--factory`. 

The readme in this [link](https://github.com/Open-Attestation/token-registry#advanced-usage) gives a more detailed explanation on using your own factory contract.

Let me know if I have managed to make things a little clearer for you.😊

**Comment by marlowl** [comment] 2023-03-22 17:55
@superical thanks, that already clarifies some things! :smile:

> Oh wait, I just read the title of your post and I wondered if I've misunderstood your question. Did you mean you passed in the `--factory` with your own factory but it is still deployed with the default factory?

Correct, this is what I meant. See the above given hardhat example commands

**Comment by superical** [comment] 2023-03-22 20:00
Ahh! Ok, I just remembered this issue. During the beta phase, `--factory` worked with and without being in `--standalone` mode. However, it was ultimately decided (and implemented in #101) that it'd be best for our deployer to only accept whitelisted factories, which is the address you are seeing in the logs. Then it slipped off my mind that the readme hasn't reflected this change yet.🤦‍♂️

Simply put, the `--factory` option will only work with the `--standalone` flag. For the same reason, I have updated my previous comment to make this part clear.

I have also updated the readme which was still stating the beta behaviour.

Thanks for raising this issue!!😃🙇‍♂️

**Comment by marlowl** [comment] 2023-03-23 08:18
@superical  I tried out your suggestion and that indeed does the trick!

In the meantime, I observed that the open-attestation-cli tool exhibits the same behavior when executing the token deploy [command](https://github.com/Open-Attestation/open-attestation-cli#deploy-new-token-registry) with the `--factory` flag provided. Is the `--standalone` functionality also available from within the token-registry npm package? 

Thanks for the quick responses! 😄

**Comment by superical** [comment] 2023-03-23 10:52
Great to know that it works for you now!😃

Umm... You might be right about a similar issue in the CLI too. In case I'm giving wrong info about the CLI, I've created an issue in the CLI repo and linked it to this one and sought my teammate @puayhiang to help to have a look at your issue. He is our CLI guru who did the recent update in the CLI to use the v4 contracts and he knows much better about the CLI than I do.😁

**Comment by marlowl** [comment] 2023-03-23 14:04
@superical @puayhiang Thanks for following up on this, will keep an eye on the issue! 😄 

From our side, we started experimenting with the newly merged  v4 releases throughout the TradeTrust/OA codebases. Not fully sure if the full v4 version is already 'officially' rolled out and ready for battle-testing?

**Comment by superical** [comment] 2023-03-24 05:21
Very cool to hear that you have started experimenting with the v4 releases!😀

**Comment by superical** [comment] 2023-03-24 09:16
Good question, @marlowl! I've been wondering about that too.😂 From what I heard in our recent chat, it's supposed to be wrapped up by this week, but to be honest, it's Friday evening here and I'm not holding my breath. I'm staying hopeful about next week or, maybe, soon™️.

@helenheaptt It would be amazing if you could give @marlowl a heads up when the report is all set to be published. I'm pretty sure he will appreciate it. He is already experimenting building with the v4 contracts. Sounds pretty cool to me! 😉

**Comment by marlowl** [comment] 2023-03-24 09:53
@superical @helenheaptt  Simply tag my GitHub handle and I'll be notified through Github.

Thank you for clarifying and have a good weekend! 🙏🏻

**Comment by superical** [comment] 2023-03-24 10:19
Thanks everyone! I'll close this issue for now. Feel free to reply to (or even reopen) this issue on any new updates.🙏

**Closed by superical** 2023-03-24 10:19 UTC
